'use server';

/**
 * @fileOverview AI-powered writing assistant to suggest improvements to writing style and grammar.
 *
 * - improveWritingStyle - A function that takes text and returns improved text.
 * - ImproveWritingStyleInput - The input type for the improveWritingStyle function.
 * - ImproveWritingStyleOutput - The return type for the improveWritingStyle function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ImproveWritingStyleInputSchema = z.object({
  text: z.string().describe('The text to improve.'),
});
export type ImproveWritingStyleInput = z.infer<typeof ImproveWritingStyleInputSchema>;

const ImproveWritingStyleOutputSchema = z.object({
  improvedText: z.string().describe('The improved text.'),
  feedback: z.string().describe('Feedback on the original text and changes made.'),
});
export type ImproveWritingStyleOutput = z.infer<typeof ImproveWritingStyleOutputSchema>;

export async function improveWritingStyle(input: ImproveWritingStyleInput): Promise<ImproveWritingStyleOutput> {
  return improveWritingStyleFlow(input);
}

const improveWritingStylePrompt = ai.definePrompt({
  name: 'improveWritingStylePrompt',
  input: {schema: ImproveWritingStyleInputSchema},
  output: {schema: ImproveWritingStyleOutputSchema},
  prompt: `You are an AI writing assistant that improves writing style and grammar. You will receive text and return improved text, as well as provide feedback on the original text and changes made.

Original Text: {{{text}}}

Improved Text:`, // The improved text will be generated by the LLM
});

const improveWritingStyleFlow = ai.defineFlow(
  {
    name: 'improveWritingStyleFlow',
    inputSchema: ImproveWritingStyleInputSchema,
    outputSchema: ImproveWritingStyleOutputSchema,
  },
  async input => {
    const {output} = await improveWritingStylePrompt(input);
    return output!;
  }
);
