
'use client';

import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { ArrowLeft, FileText, Gavel, Scale, ShieldCheck } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { ScrollArea } from '@/components/ui/scroll-area';

export default function TermsOfServicePage() {
  const router = useRouter();

  return (
    <div className="max-w-4xl mx-auto space-y-10 py-10 px-4 pb-32 animate-in fade-in duration-700">
      <header className="space-y-1">
        <Button variant="ghost" onClick={() => router.push('/settings')} className="mb-2 -ml-2 text-muted-foreground hover:text-foreground">
            <ArrowLeft className="mr-2 h-4 w-4" /> Back to Settings
        </Button>
        <h1 className="text-3xl md:text-5xl font-headline font-bold text-foreground flex items-center gap-4">
            <FileText className="h-10 w-10 text-primary" /> Terms of Service
        </h1>
        <p className="text-muted-foreground text-sm font-medium">Protocol Update: May 15, 2026</p>
      </header>
      
      <div className="grid gap-8">
        <Card className="rounded-[2.5rem] border-border/40 shadow-xl bg-card/40 backdrop-blur-sm overflow-hidden">
            <CardHeader className="bg-primary/5 border-b border-primary/10 p-8">
                <CardTitle className="text-xl flex items-center gap-3">
                    <Scale className="h-6 w-6 text-primary" /> Community Contract
                </CardTitle>
                <CardDescription>Legal framework for our literary multiverse.</CardDescription>
            </CardHeader>
            <CardContent className="p-8 prose dark:prose-invert max-w-none text-sm md:text-base leading-relaxed text-foreground/80">
                <section>
                    <h3 className="text-foreground font-bold">1. The Creative License</h3>
                    <p>At D4RKV3NOM, you remain the sole owner of your intellectual property. By publishing a manuscript on our platform, you grant us a worldwide, non-exclusive, royalty-free license to host, display, and distribute your work. You can withdraw this license at any time by deleting your manuscript.</p>
                </section>

                <section>
                    <h3 className="text-foreground font-bold">2. Community Behavior & Safety</h3>
                    <p>Our platform embraces a "Dark Aesthetic," but our community values safety. We have zero tolerance for hate speech, harassment, or non-consensual use of others' characters/content. Violation of these standards will result in immediate account termination.</p>
                </section>

                <section>
                    <h3 className="text-foreground font-bold">3. AI-Assisted Writing</h3>
                    <p>Writers are permitted to use AI tools (like our built-in Writing Assistant) to enhance their work. However, you must explicitly disclose if a manuscript is entirely generated by AI. We reserve the right to label content accordingly to maintain transparency.</p>
                </section>

                <section>
                    <h3 className="text-foreground font-bold">4. Premium Access & Transactions</h3>
                    <p>Authors may restrict chapters to "Premium Access." Users granted this access are prohibited from redistributing or leaking private content. Any detected breach of this protocol will lead to a permanent ban from the archives.</p>
                </section>

                <section>
                    <h3 className="text-foreground font-bold">5. Platform Node Reliability</h3>
                    <p>D4RKV3NOM is a distributed environment utilizing advanced local persistence. We are not liable for data loss occurring due to hardware failure on the user's end. We recommend using our "Cloud Sync" feature regularly.</p>
                </section>
            </CardContent>
            <footer className="p-6 bg-muted/20 border-t border-border/20 text-center">
                <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/40">Gavel Protocol & bull; D4RKV3NOM Core Governance</p>
            </footer>
        </Card>
      </div>
    </div>
  );
}
